### ISSUE TITLE
 Verificar Estado + Ciudad + Municipios + Parroquias

### ISSUE THREAD

**Issue by jgjimenez** [marydn/venezuela-sql#5]
Saludos, excelente trabajo.

Estoy viendo que la relación en la BD es Estado - Ciudad / Estado - Municipios - Parroquias.

Debería ser: Estado - Ciudad - Municipio - Parroquia

o estoy errado? si es así, entonces se debe corregir las asignación de datos a cada tabla.

![SQL Venezuela](https://user-images.githubusercontent.com/1020119/120930369-003b4380-c6bb-11eb-8d2a-b6e1a5507865.png)

**Comment by marydn** [comment]
Hola! Gracias por escribir. No estoy segura de entender el problema. ¿El esquema que has dibujado propone la solución? ¿Tienes una PR que pueda ver?

**Comment by jgjimenez** [comment]
Hola! un gusto recibir tu mensaje

El esquema es tal cual esta creado venezuela.sql, lo ideal seria que la clave foránea de municipios se encuentre en ciudades, para mantener la relacion Estado - Ciudad - Municipio - Parroquia.

pensé que era error de la clave foránea pero los datos almacenados apunta a estados - municipios.

Saludos.

**Comment by marydn** [comment]
Ah, vale, ahora entiendo. ¿Crees que podrías hacer una PR para solucionarlo?

**Comment by jgjimenez** [comment]
Estoy terminado un sistema punto de venta en c# y luego me apunto a esa.

Revisé ciudades de amazonas y las otras y es muy complejo, he encontrado el censo y proyecciones de Venezuela y el mismo caso. al final tu SQL esta muy bien. pero será muy difícil saber un municipio de una ciudad en un estado con tres ciudades y 7 municipios.

entonces, si ejecutara este SQL en unos combobox llamando a estados luego ciudades el combobox de municipio sabrá que ya tengo seleccionado estados y sus municipios sin distingo de ciudades.

Saludos y Me encanto tu trabajo. Feliz Día
